name: deploy.yml
on:
  push:
    branches:
      - master

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: 'frontend-build'
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/download-artifact@v8.0.1
        with:
          name: 'frontend-build'
          path: backend/src/main/resources/static

      - name: Setup JDK
        uses: actions/setup-java@v6.0.1
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: 'app.jar'
          path: backend/target/app.jar

  push-to-dockerHub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/download-artifact@v8.0.1
        with:
          name: 'app.jar'
          path: backend/target

      - name: Login to Dockerhub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v7.3.0
        with:
          push: 'true'
          tags: ${{ secrets.DOCKERHUB_TAG }}
          context: .

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: push-to-dockerHub
    environment:
      name: '180-boards-for-darts'
      url: 'https://one80-boards-for-darts-latest.onrender.com'
    steps:
      - name: deploy-to-render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}